export interface IntegrationConfig {
  id: string;
  name: string;
  description: string;
  image: string;
  category: "Social" | "Review Platform" | "App Store" | "Search";
}

export const authorizedIntegrations: IntegrationConfig[] = [
  {
    id: "google-business",
    name: "Google Business Profile",
    description: "Manage reviews and Q&A from Google Search and Maps.",
    image: "/authorized/Google.png",
    category: "Search",
  },
  {
    id: "facebook",
    name: "Facebook",
    description:
      "Connect your Facebook Pages to manage recommendations and reviews.",
    image: "/authorized/Facebook-Logo.png",
    category: "Social",
  },
  {
    id: "trustpilot",
    name: "Trustpilot",
    description: "Automate review collection and display verified reviews.",
    image: "/authorized/trustpilot-logo.png",
    category: "Review Platform",
  },
  {
    id: "bing-places",
    name: "Bing Places",
    description: "Sync reviews from Bing Places for Business.",
    image: "/authorized/bing-logo.png",
    category: "Search",
  },
  {
    id: "apple-business",
    name: "Apple Business Connect",
    description: "Manage your presence across Apple Maps and other Apple apps.",
    image: "/authorized/apple_business-logo.png",
    category: "Search",
  },
  {
    id: "google-play",
    name: "Google Play Store",
    description: "Monitor and reply to app reviews on the Google Play Store.",
    image: "/authorized/google_play-logo.png",
    category: "App Store",
  },
  {
    id: "app-store",
    name: "Apple App Store",
    description: "Track ratings and reviews for your iOS apps.",
    image: "/authorized/app_store-logo.png",
    category: "App Store",
  },
];

export const indexedIntegrations: IntegrationConfig[] = [
  {
    id: "google-search",
    name: "Google Search",
    description: "Track public reviews and ratings from Google Search results.",
    image: "/indexed/google_idx.png",
    category: "Search",
  },
  {
    id: "bing-search",
    name: "Bing Search",
    description: "Monitor public reviews on Bing.",
    image: "/authorized/bing-logo.png",
    category: "Search",
  },
  {
    id: "trustpilot-public",
    name: "Trustpilot Public",
    description: "Track competitor reviews on Trustpilot.",
    image: "/indexed/trustpilot-index-logo.png",
    category: "Review Platform",
  },
  {
    id: "facebook-public",
    name: "Facebook Public",
    description: "Monitor public Facebook recommendations.",
    image: "/indexed/reviewshakefacebook-logo.png",
    category: "Social",
  },
  {
    id: "airbnb",
    name: "Airbnb",
    description: "Monitor property reviews and ratings on Airbnb.",
    image: "/indexed/airbnb-logo.png",
    category: "Review Platform",
  },
  {
    id: "angies-list",
    name: "Angie's List",
    description: "Monitor reviews on Angie's List.",
    image: "/indexed/angies-logo.png",
    category: "Review Platform",
  },
  {
    id: "apartments-com",
    name: "Apartments.com",
    description: "Track rental reviews on Apartments.com.",
    image: "/indexed/apartment-logo.png",
    category: "Review Platform",
  },
  {
    id: "app-store-index",
    name: "Apple App Store (Public)",
    description: "Monitor public App Store reviews.",
    image: "/indexed/app_store_index-logo.png",
    category: "App Store",
  },
  {
    id: "avvo",
    name: "Avvo",
    description: "Track legal reviews and ratings on Avvo.",
    image: "/indexed/avvo-logo.png",
    category: "Review Platform",
  },
  {
    id: "bbb",
    name: "Better Business Bureau",
    description: "Monitor your BBB accreditation and reviews.",
    image: "/indexed/bbbLogo.png",
    category: "Review Platform",
  },
  {
    id: "booking-com",
    name: "Booking.com",
    description: "Track hotel and property reviews on Booking.com.",
    image: "/indexed/booking_index-logo.png",
    category: "Review Platform",
  },
  {
    id: "capterra",
    name: "Capterra",
    description: "Monitor software reviews on Capterra.",
    image: "/indexed/capterra-logo.png",
    category: "Review Platform",
  },
  {
    id: "car-dealer-reviews",
    name: "Car Dealer Reviews",
    description: "Track reviews on Car Dealer Reviews.",
    image: "/indexed/Car-Dealer-Reviews-Logo.png",
    category: "Review Platform",
  },
  {
    id: "cargurus",
    name: "CarGurus",
    description: "Monitor automotive reviews on CarGurus.",
    image: "/indexed/cargurus-logo.png",
    category: "Review Platform",
  },
  {
    id: "cars-com",
    name: "Cars.com",
    description: "Track dealership reviews on Cars.com.",
    image: "/indexed/cars-logo.png",
    category: "Review Platform",
  },
  {
    id: "cellarpass",
    name: "CellarPass",
    description: "Monitor reviews on CellarPass.",
    image: "/indexed/cellarpass.png",
    category: "Review Platform",
  },
  {
    id: "dealerrater",
    name: "DealerRater",
    description: "Track automotive dealer reviews on DealerRater.",
    image: "/indexed/dealerrater-logo.png",
    category: "Review Platform",
  },
  {
    id: "doordash",
    name: "DoorDash",
    description: "Monitor food delivery reviews on DoorDash.",
    image: "/indexed/doordash-logo.png",
    category: "Review Platform",
  },
  {
    id: "edmunds",
    name: "Edmunds",
    description: "Track automotive reviews on Edmunds.",
    image: "/indexed/edmunds-logo.png",
    category: "Review Platform",
  },
  {
    id: "expedia",
    name: "Expedia",
    description: "Monitor travel reviews on Expedia.",
    image: "/indexed/expedia-card.png",
    category: "Review Platform",
  },
  {
    id: "foursquare",
    name: "Foursquare",
    description: "Track tips and reviews on Foursquare.",
    image: "/indexed/fourSquare-logo.png",
    category: "Social",
  },
  {
    id: "glassdoor",
    name: "Glassdoor",
    description: "Monitor employee reviews on Glassdoor.",
    image: "/indexed/glassdoor-logo.png",
    category: "Review Platform",
  },
  {
    id: "grubhub",
    name: "Grubhub",
    description: "Track food delivery reviews on Grubhub.",
    image: "/indexed/grubhub-logo.png",
    category: "Review Platform",
  },
  {
    id: "g2",
    name: "G2",
    description: "Monitor software reviews on G2.",
    image: "/indexed/gtwo-logo.png",
    category: "Review Platform",
  },
  {
    id: "healthgrades",
    name: "Healthgrades",
    description: "Track healthcare provider reviews on Healthgrades.",
    image: "/indexed/Healthgrades-logo.png",
    category: "Review Platform",
  },
  {
    id: "homeadvisor",
    name: "HomeAdvisor",
    description: "Monitor home service reviews on HomeAdvisor.",
    image: "/indexed/homeadvisor-logo.png",
    category: "Review Platform",
  },
  {
    id: "homestars",
    name: "HomeStars",
    description: "Track home improvement reviews on HomeStars.",
    image: "/indexed/homestars-logo.png",
    category: "Review Platform",
  },
  {
    id: "hostelworld",
    name: "Hostelworld",
    description: "Monitor hostel reviews on Hostelworld.",
    image: "/indexed/hostelworld-logo.png",
    category: "Review Platform",
  },
  {
    id: "hotels-com",
    name: "Hotels.com",
    description: "Track hotel reviews on Hotels.com.",
    image: "/indexed/hotels.png",
    category: "Review Platform",
  },
  {
    id: "houzz",
    name: "Houzz",
    description: "Monitor home design and remodeling reviews on Houzz.",
    image: "/indexed/houzz-logo.png",
    category: "Review Platform",
  },
  {
    id: "indeed",
    name: "Indeed",
    description: "Track company reviews on Indeed.",
    image: "/indexed/indeed.png",
    category: "Review Platform",
  },
  {
    id: "lawyers-com",
    name: "Lawyers.com",
    description: "Monitor legal reviews on Lawyers.com.",
    image: "/indexed/lawyers-logo.png",
    category: "Review Platform",
  },
  {
    id: "opentable",
    name: "OpenTable",
    description: "Track restaurant reviews on OpenTable.",
    image: "/indexed/opentable.png",
    category: "Review Platform",
  },
  {
    id: "productreview",
    name: "ProductReview",
    description: "Monitor product reviews on ProductReview.com.au.",
    image: "/indexed/productreview-logo.png",
    category: "Review Platform",
  },
  {
    id: "ratemds",
    name: "RateMDs",
    description: "Track doctor and health facility reviews on RateMDs.",
    image: "/indexed/ratemds-logo.png",
    category: "Review Platform",
  },
  {
    id: "rent-com",
    name: "Rent.com",
    description: "Monitor rental property reviews on Rent.com.",
    image: "/indexed/rent-logo.png",
    category: "Review Platform",
  },
  {
    id: "talabat",
    name: "Talabat",
    description: "Track food delivery reviews on Talabat.",
    image: "/indexed/talabat-logo.png",
    category: "Review Platform",
  },
  {
    id: "trusted-shops",
    name: "Trusted Shops",
    description: "Monitor e-commerce reviews on Trusted Shops.",
    image: "/indexed/trustedshops-logo.png",
    category: "Review Platform",
  },
  {
    id: "trustradius",
    name: "TrustRadius",
    description: "Track software reviews on TrustRadius.",
    image: "/indexed/trustradius-logo.png",
    category: "Review Platform",
  },
  {
    id: "uber-eats",
    name: "Uber Eats",
    description: "Monitor food delivery reviews on Uber Eats.",
    image: "/indexed/ubereats-logo.png",
    category: "Review Platform",
  },
  {
    id: "vitals",
    name: "Vitals",
    description: "Track doctor and patient reviews on Vitals.",
    image: "/indexed/vitals-logo.png",
    category: "Review Platform",
  },
  {
    id: "zillow",
    name: "Zillow",
    description: "Monitor real estate reviews on Zillow.",
    image: "/indexed/zillow-logo.png",
    category: "Review Platform",
  },
  {
    id: "zocdoc",
    name: "Zocdoc",
    description: "Track medical provider reviews on Zocdoc.",
    image: "/indexed/zocdoc-logo.png",
    category: "Review Platform",
  },
  {
    id: "zomato",
    name: "Zomato",
    description: "Monitor restaurant reviews on Zomato.",
    image: "/indexed/zomato-logo.png",
    category: "Review Platform",
  },
];

// For backward compatibility if needed, but we should switch to specific exports
export const integrations = authorizedIntegrations;
